# 正式服务器

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: songyanan521
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
upload:
  root: C:/nginx-1.14.2/html/upload/