# 测试服务器
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
server:
  port: 8081

# 正式服务器

#spring:
#  datasource:
#    url: jdbc:mysql://123.206.122.67:3306/blog?serverTimezone=GMT%2B8
#    username: root
#    password: songyanan521
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: true
##    show-sql: true
#server:
#  port: 8088